### ISSUE TITLE
Issue with open and close tabs

### ISSUE THREAD

**Issue by newUserRepo** [PacktPublishing/Data-Centric-Applications-with-Vaadin-8#2]
Hello, 

what a great job, when I try to navigate with the options of the tabs, this error originates, similarly when closing a tab and reopening it this originates, only with vaadin 10, with vaadin 8 works perfect

![issuetabs](https://user-images.githubusercontent.com/36064164/48010158-57509480-e11d-11e8-8e58-7df3b178c400.gif)

![errortabs2](https://user-images.githubusercontent.com/36064164/48010110-4011a700-e11d-11e8-8f50-589be6fd9160.gif)

this code simply creates two tabs, nothing special, I compile the project correctly, but that strange error originates

```` /**
 * @author Alejandro Duarte
 */
public class ExampleModule implements AppModule {

    private ApplicationLayout layout;

    @Override
    public void register(ApplicationLayout layout) {
        this.layout = layout;
        menuOption("Basic Form", new TestClass());
        menuOption("Form Responsive", new FormResponsive());

    }

    private void menuOption(final String caption, Component c) {
        final ApplicationLayout.MenuOption menu = new ApplicationLayout.MenuOption(caption);
        layout.addMenuOption(menu,(o) -> {
            Notification.show(caption);
            final ApplicationLayout.WorkingAreaComponent awc = new ApplicationLayout.WorkingAreaComponent(caption,c);
            layout.addWorkingAreaComponent(awc);
        });
    }

}
````

### **Output**

> [qtp944009919-16] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
java.lang.IllegalArgumentException: The 'component' parameter cannot be null
	at com.vaadin.flow.component.HasOrderedComponents.indexOf(HasOrderedComponents.java:84)
	at com.vaadin.flow.component.tabs.Tabs.setSelectedTab(Tabs.java:139)
	at org.vaadin.tabs.PagedTabs.select(PagedTabs.java:37)
	at org.vaadin.tabs.PagedTabs.select(PagedTabs.java:43)
	at packt.vaadin.datacentric.chapter02.api.TabBasedApplicationLayout.showComponent(TabBasedApplicationLayout.java:117)
	at packt.vaadin.datacentric.chapter02.api.TabBasedApplicationLayout.addWorkingAreaComponent(TabBasedApplicationLayout.java:84)
	at packt.vaadin.datacentric.chapter02.api.TabBasedApplicationLayout.addWorkingAreaComponent(TabBasedApplicationLayout.java:75)
	at packt.vaadin.datacentric.chapter02.example.module.ExampleModule.lambda$menuOption$e4d32b92$1(ExampleModule.java:29)
	at packt.vaadin.datacentric.chapter02.api.TabBasedApplicationLayout.lambda$addMenuOption$5669783c$1(TabBasedApplicationLayout.java:100)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:132)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:326)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$5ee67f2b$1(ComponentEventBus.java:190)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:378)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:378)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:58)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:63)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:377)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:367)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:367)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1493)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:300)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

**Comment by alejandro-du** [comment]
Fixed. Please, pull the changes and try again. Reopen if the issue persists.

**Comment by newUserRepo** [comment]
the issue persists :s 

vaadin 8 , good
![vaadin8good](https://user-images.githubusercontent.com/36064164/48170235-e8c72e80-e2f6-11e8-8f54-e79eb2a297ce.gif)


vaadin 10 not good.. why? and stacktrace is empty
![issuevaadin10tabs](https://user-images.githubusercontent.com/36064164/48170195-b4ec0900-e2f6-11e8-94b5-6a5fa166b131.gif)

**Comment by alejandro-du** [comment]
Which version of `paged-tabs` are you using and how are you adding the tabs on the button click events?

**Comment by newUserRepo** [comment]
Hi, 

version of paged-tabs is 1.1.2

````
package packt.vaadin.datacentric.chapter02.example.module;

import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.notification.Notification;
import packt.vaadin.datacentric.chapter02.api.AppModule;
import packt.vaadin.datacentric.chapter02.api.ApplicationLayout;

/**
 * @author Alejandro Duarte
 */
public class ExampleModule implements AppModule {

    private ApplicationLayout layout;
    @Override
    public void register(ApplicationLayout layout) {
        this.layout = layout;
        menuOption("Basic Form", new TestClass());
        menuOption("Form Responsive", new FormResponsive());

    }

    private void menuOption(final String caption, Component c) {
        final ApplicationLayout.MenuOption menu = new ApplicationLayout.MenuOption(caption);
        layout.addMenuOption(menu,(o) -> {
            Notification.show(caption);
            final ApplicationLayout.WorkingAreaComponent awc = new ApplicationLayout.WorkingAreaComponent(caption,c);
            layout.addWorkingAreaComponent(awc);
        });
    }
}
````

**Comment by alejandro-du** [comment]
It works as intended. The component is not added if it already exists.

**Comment by rucko24** [comment]
Hello Alejandro, what's up? Could you show me a minimum example of how to do it correctly? greetings my doc.

**Comment by alejandro-du** [comment]
> Hello Alejandro, what's up? Could you show me a minimum example of how to do it correctly with vaadin 10 or above? greetings my doc.

What do you mean? This is actually for Vaadin 10+.

**Comment by rucko24** [comment]
Hi a Little example for vaadin 10.

**Comment by alejandro-du** [comment]
See the book's examples. Cheers.
